version: '3.1'

services:
  web:
    container_name: visualization_portal_nginx
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/vhosts:/etc/nginx/conf.d/vhosts"
      - "../source:/var/www/html"
    ports:
      - "8000:80"
      - "8080:8080"
    depends_on:
      - php
  php:
    container_name: visualization_portal_php
    build: php-fpm-debug/
    volumes:
      - "../source:/var/www/html"
    environment:
      - LOCAL_DEV=1
      - SCALYR_READ_KEY="yourkeyhere"
  grafana:
    container_name: visualization_grafana
    image: grafana/grafana:5.0.0
    ports:
      - "3000:3000"


